# Don't change this
theme: jekyll-theme-primer

# GitHub project
baseurl: /nmos-system

# Which relase or branch appears in header links and on the home page
default_tree: branches/master # alternatively e.g. branches/v1.0.x or tags/v1.0

# Regex patterns of tags (releases) and branches to show
show_tags: v[0-9]*\.[0-9]*
show_branches: v[0-9]*\.[0-9]*|master
